name: AWS OIDC test
on:
  push:
    branches: [ main ]   # push from the repo itself, not a fork
  workflow_dispatch:

permissions:
  id-token: write   # <-- REQUIRED for OIDC
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<476488972684>:role/GitHubCdkDeployRole
          aws-region: us-east-1

      - name: Who am I?
        run: aws sts get-caller-identity
